/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.SBIBanking.model;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-25-2009
 * 
 * XDoclet definition:
 * @struts.form name="bankchequeRequestForm"
 */
public class BankChequeRequestForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** loginid property */
	private String loginid;
	
	private String chequebookrequest;

	/** accountno property */
	private String accountno;

	/** previousChequeBookStatus property */
	private String previousChequeBookStatus;

	/** status property */
	private String status;

	/** requestid property */
	private int requestid;

	/** requestDate property */
	private String requestDate;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the loginid.
	 * @return String
	 */
	public String getLoginid() {
		return loginid;
	}

	/** 
	 * Set the loginid.
	 * @param loginid The loginid to set
	 */
	public void setLoginid(String loginid) {
		this.loginid = loginid;
	}

	/** 
	 * Returns the accountno.
	 * @return String
	 */
	public String getAccountno() {
		return accountno;
	}

	/** 
	 * Set the accountno.
	 * @param accountno The accountno to set
	 */
	public void setAccountno(String accountno) {
		this.accountno = accountno;
	}

	/** 
	 * Returns the previousChequeBookStatus.
	 * @return String
	 */
	public String getPreviousChequeBookStatus() {
		return previousChequeBookStatus;
	}

	/** 
	 * Set the previousChequeBookStatus.
	 * @param previousChequeBookStatus The previousChequeBookStatus to set
	 */
	public void setPreviousChequeBookStatus(String previousChequeBookStatus) {
		this.previousChequeBookStatus = previousChequeBookStatus;
	}

	/** 
	 * Returns the status.
	 * @return String
	 */
	public String getStatus() {
		return status;
	}

	/** 
	 * Set the status.
	 * @param status The status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/** 
	 * Returns the requestid.
	 * @return int
	 */
	public int getRequestid() {
		return requestid;
	}

	/** 
	 * Set the requestid.
	 * @param requestid The requestid to set
	 */
	public void setRequestid(int requestid) {
		this.requestid = requestid;
	}

	/** 
	 * Returns the requestDate.
	 * @return String
	 */
	public String getRequestDate() {
		return requestDate;
	}

	/** 
	 * Set the requestDate.
	 * @param requestDate The requestDate to set
	 */
	public void setRequestDate(String requestDate) {
		this.requestDate = requestDate;
	}

	public String getChequebookrequest() {
		return chequebookrequest;
	}

	public void setChequebookrequest(String chequebookrequest) {
		this.chequebookrequest = chequebookrequest;
	}
}