/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.SBIBanking.model;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-20-2009
 * 
 * XDoclet definition:
 * @struts.form name="bankServicesMasterForm"
 */
public class BankServicesMasterForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** serviceId property */
	private int serviceId;

	/** serviceName property */
	private String serviceName;

	/** serviceDesc property */
	private String serviceDesc;
	private String branchdesc;

	/** serviceActivestate property */
	private String serviceActivestate;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the serviceId.
	 * @return int
	 */
	public int getServiceId() {
		return serviceId;
	}

	/** 
	 * Set the serviceId.
	 * @param serviceId The serviceId to set
	 */
	public void setServiceId(int serviceId) {
		this.serviceId = serviceId;
	}

	/** 
	 * Returns the serviceName.
	 * @return String
	 */
	public String getServiceName() {
		return serviceName;
	}

	/** 
	 * Set the serviceName.
	 * @param serviceName The serviceName to set
	 */
	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	/** 
	 * Returns the serviceDesc.
	 * @return String
	 */
	public String getServiceDesc() {
		return serviceDesc;
	}

	/** 
	 * Set the serviceDesc.
	 * @param serviceDesc The serviceDesc to set
	 */
	public void setServiceDesc(String serviceDesc) {
		this.serviceDesc = serviceDesc;
	}

	/** 
	 * Returns the serviceActivestate.
	 * @return String
	 */
	public String getServiceActivestate() {
		return serviceActivestate;
	}

	/** 
	 * Set the serviceActivestate.
	 * @param serviceActivestate The serviceActivestate to set
	 */
	public void setServiceActivestate(String serviceActivestate) {
		this.serviceActivestate = serviceActivestate;
	}

	public String getBranchdesc() {
		return branchdesc;
	}

	public void setBranchdesc(String branchdesc) {
		this.branchdesc = branchdesc;
	}
}