/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.SBIBanking.model;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 01-20-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="bankBranchMasterForm"
 */
public class BankBranchMasterForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** branchId property */
	private int branchId;

	/** branchEmailId property */
	private String branchEmailId;

	/** branchInchrgId property */
	private int branchInchrgId;

	/** branchPhNo3 property */
	private String branchPhNo3;

	/** branchPhNo1 property */
	private String branchPhNo1;

	/** branchPhNo2 property */
	private String branchPhNo2;

	/** branchAddr property */
	private String branchAddr;
	private String status;
	private String loginname;

	/*
	 * Generated Methods
	 */

	public String getLoginname() {
		return loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * Returns the branchId.
	 * 
	 * @return int
	 */
	public int getBranchId() {
		return branchId;
	}

	/**
	 * Set the branchId.
	 * 
	 * @param branchId
	 *            The branchId to set
	 */
	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	/**
	 * Returns the branchEmailId.
	 * 
	 * @return String
	 */
	public String getBranchEmailId() {
		return branchEmailId;
	}

	/**
	 * Set the branchEmailId.
	 * 
	 * @param branchEmailId
	 *            The branchEmailId to set
	 */
	public void setBranchEmailId(String branchEmailId) {
		this.branchEmailId = branchEmailId;
	}

	/**
	 * Returns the branchInchrgId.
	 * 
	 * @return int
	 */
	public int getBranchInchrgId() {
		return branchInchrgId;
	}

	/**
	 * Set the branchInchrgId.
	 * 
	 * @param branchInchrgId
	 *            The branchInchrgId to set
	 */
	public void setBranchInchrgId(int branchInchrgId) {
		this.branchInchrgId = branchInchrgId;
	}

	/**
	 * Returns the branchPhNo3.
	 * 
	 * @return String
	 */
	public String getBranchPhNo3() {
		return branchPhNo3;
	}

	/**
	 * Set the branchPhNo3.
	 * 
	 * @param branchPhNo3
	 *            The branchPhNo3 to set
	 */
	public void setBranchPhNo3(String branchPhNo3) {
		this.branchPhNo3 = branchPhNo3;
	}

	/**
	 * Returns the branchPhNo1.
	 * 
	 * @return String
	 */
	public String getBranchPhNo1() {
		return branchPhNo1;
	}

	/**
	 * Set the branchPhNo1.
	 * 
	 * @param branchPhNo1
	 *            The branchPhNo1 to set
	 */
	public void setBranchPhNo1(String branchPhNo1) {
		this.branchPhNo1 = branchPhNo1;
	}

	/**
	 * Returns the branchPhNo2.
	 * 
	 * @return String
	 */
	public String getBranchPhNo2() {
		return branchPhNo2;
	}

	/**
	 * Set the branchPhNo2.
	 * 
	 * @param branchPhNo2
	 *            The branchPhNo2 to set
	 */
	public void setBranchPhNo2(String branchPhNo2) {
		this.branchPhNo2 = branchPhNo2;
	}

	/**
	 * Returns the branchAddr.
	 * 
	 * @return String
	 */
	public String getBranchAddr() {
		return branchAddr;
	}

	/**
	 * Set the branchAddr.
	 * 
	 * @param branchAddr
	 *            The branchAddr to set
	 */
	public void setBranchAddr(String branchAddr) {
		this.branchAddr = branchAddr;
	}
}