/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.SBIBanking.model;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-13-2009
 * 
 * XDoclet definition:
 * @struts.form name="/branchServiceMaster"
 */
public class BranchServcesMaster extends ActionForm {
	/*
	 * Generated fields
	 */

	/** branchId property */
	private int branchId;

	/** serviceid property */
	private int serviceid;
	
	private int accounttypeid;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	
	private String servicename;
	private String servicedesc;
	private String serviceActivestate;
	public String getServicename() {
		return servicename;
	}

	public void setServicename(String servicename) {
		this.servicename = servicename;
	}

	public String getServicedesc() {
		return servicedesc;
	}

	public void setServicedesc(String servicedesc) {
		this.servicedesc = servicedesc;
	}

	public String getServiceActivestate() {
		return serviceActivestate;
	}

	public void setServiceActivestate(String serviceActivestate) {
		this.serviceActivestate = serviceActivestate;
	}

	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the branchId.
	 * @return int
	 */
	public int getBranchId() {
		return branchId;
	}

	/** 
	 * Set the branchId.
	 * @param branchId The branchId to set
	 */
	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	/** 
	 * Returns the serviceid.
	 * @return int
	 */
	public int getServiceid() {
		return serviceid;
	}

	/** 
	 * Set the serviceid.
	 * @param serviceid The serviceid to set
	 */
	public void setServiceid(int serviceid) {
		this.serviceid = serviceid;
	}

	public int getAccounttypeid() {
		return accounttypeid;
	}

	public void setAccounttypeid(int accounttypeid) {
		this.accounttypeid = accounttypeid;
	}
}