/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.SBIBanking.model;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-17-2009
 * 
 * XDoclet definition:
 * @struts.form name="customerTransacationmodel"
 */
public class CustomerTransactionModel extends ActionForm {
	/*
	 * Generated fields
	 */

	/** transactiontype property */
	private String transactiontype;

	/** amount property */
	private int amount;

	/** branchname property */
	private String branchname;

	/** accountno property */
	private String accountno;

	/** transactionid property */
	private int transactionid;

	/** transactionDate property */
	private String transactionDate;

	/** employeename property */
	private String employeename;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	
	
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the transactiontype.
	 * @return String
	 */
	public String getTransactiontype() {
		return transactiontype;
	}

	/** 
	 * Set the transactiontype.
	 * @param transactiontype The transactiontype to set
	 */
	public void setTransactiontype(String transactiontype) {
		this.transactiontype = transactiontype;
	}

	/** 
	 * Returns the amount.
	 * @return int
	 */
	public int getAmount() {
		return amount;
	}

	/** 
	 * Set the amount.
	 * @param amount The amount to set
	 */
	public void setAmount(int amount) {
		this.amount = amount;
	}

	/** 
	 * Returns the branchname.
	 * @return String
	 */
	public String getBranchname() {
		return branchname;
	}

	/** 
	 * Set the branchname.
	 * @param branchname The branchname to set
	 */
	public void setBranchname(String branchname) {
		this.branchname = branchname;
	}

	/** 
	 * Returns the accountno.
	 * @return String
	 */
	public String getAccountno() {
		return accountno;
	}

	/** 
	 * Set the accountno.
	 * @param accountno The accountno to set
	 */
	public void setAccountno(String accountno) {
		this.accountno = accountno;
	}

	/** 
	 * Returns the transactionid.
	 * @return int
	 */
	public int getTransactionid() {
		return transactionid;
	}

	/** 
	 * Set the transactionid.
	 * @param transactionid The transactionid to set
	 */
	public void setTransactionid(int transactionid) {
		this.transactionid = transactionid;
	}

	/** 
	 * Returns the transactionDate.
	 * @return String
	 */
	public String getTransactionDate() {
		return transactionDate;
	}

	/** 
	 * Set the transactionDate.
	 * @param transactionDate The transactionDate to set
	 */
	public void setTransactionDate(String transactionDate) {
		this.transactionDate = transactionDate;
	}

	/** 
	 * Returns the employeename.
	 * @return String
	 */
	public String getEmployeename() {
		return employeename;
	}

	/** 
	 * Set the employeename.
	 * @param employeename The employeename to set
	 */
	public void setEmployeename(String employeename) {
		this.employeename = employeename;
	}
}