/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.SBIBanking.model;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-26-2009
 * 
 * XDoclet definition:
 * @struts.form name="stoppaymentmodel"
 */
public class StopPaymentModule extends ActionForm {
	/*
	 * Generated fields
	 */

	/** chequedate property */
	private String chequedate;
private String status;

	/** amount property */
	private String amount;

	/** accountno property */
	private String accountno;

	/** stoppaymentid property */
	private int stoppaymentid;

	/** reasonforstopping property */
	private String reasonforstopping;

	/** employeename property */
	private String employeename;

	/** stoppaymentdate property */
	private String stoppaymentdate;

	/** chequeno property */
	private String chequeno;
	private String loginid;

	/*
	 * Generated Methods
	 */

	public String getLoginid() {
		return loginid;
	}

	public void setLoginid(String loginid) {
		this.loginid = loginid;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the chequedate.
	 * @return String
	 */
	public String getChequedate() {
		return chequedate;
	}

	/** 
	 * Set the chequedate.
	 * @param chequedate The chequedate to set
	 */
	public void setChequedate(String chequedate) {
		this.chequedate = chequedate;
	}

	/** 
	 * Returns the amount.
	 * @return String
	 */
	public String getAmount() {
		return amount;
	}

	/** 
	 * Set the amount.
	 * @param amount The amount to set
	 */
	public void setAmount(String amount) {
		this.amount = amount;
	}

	/** 
	 * Returns the accountno.
	 * @return String
	 */
	public String getAccountno() {
		return accountno;
	}

	/** 
	 * Set the accountno.
	 * @param accountno The accountno to set
	 */
	public void setAccountno(String accountno) {
		this.accountno = accountno;
	}

	/** 
	 * Returns the stoppaymentid.
	 * @return int
	 */
	public int getStoppaymentid() {
		return stoppaymentid;
	}

	/** 
	 * Set the stoppaymentid.
	 * @param stoppaymentid The stoppaymentid to set
	 */
	public void setStoppaymentid(int stoppaymentid) {
		this.stoppaymentid = stoppaymentid;
	}

	/** 
	 * Returns the reasonforstopping.
	 * @return String
	 */
	public String getReasonforstopping() {
		return reasonforstopping;
	}

	/** 
	 * Set the reasonforstopping.
	 * @param reasonforstopping The reasonforstopping to set
	 */
	public void setReasonforstopping(String reasonforstopping) {
		this.reasonforstopping = reasonforstopping;
	}

	/** 
	 * Returns the employeename.
	 * @return String
	 */
	public String getEmployeename() {
		return employeename;
	}

	/** 
	 * Set the employeename.
	 * @param employeename The employeename to set
	 */
	public void setEmployeename(String employeename) {
		this.employeename = employeename;
	}

	/** 
	 * Returns the stoppaymentdate.
	 * @return String
	 */
	public String getStoppaymentdate() {
		return stoppaymentdate;
	}

	/** 
	 * Set the stoppaymentdate.
	 * @param stoppaymentdate The stoppaymentdate to set
	 */
	public void setStoppaymentdate(String stoppaymentdate) {
		this.stoppaymentdate = stoppaymentdate;
	}

	/** 
	 * Returns the chequeno.
	 * @return String
	 */
	public String getChequeno() {
		return chequeno;
	}

	/** 
	 * Set the chequeno.
	 * @param chequeno The chequeno to set
	 */
	public void setChequeno(String chequeno) {
		this.chequeno = chequeno;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
}