/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;


/** 
 * MyEclipse Struts
 * Creation date: 02-19-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class BankBranchAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try{
		com.dts.SBIBanking.model.BankBranchMasterForm bForm=(com.dts.SBIBanking.model.BankBranchMasterForm)form;
		com.dts.SBIBanking.dao.BankBranchMasterDao adao=new com.dts.SBIBanking.dao.BankBranchMasterDao();
		boolean flag=adao.insertBankBranchMaster(bForm);
		if(flag){
			return mapping.findForward("success");
		}
	}catch (Exception e) {
		// TODO: handle exception
	}return mapping.findForward("fail");
}
}