/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.SBIBanking.dao.*;
import com.dts.SBIBanking.model.*;

/** 
 * MyEclipse Struts
 * Creation date: 02-12-2009
 * 
 * XDoclet definition:
 * @struts.action path="/bankServiceMasterAction" name="BankServicesMasterForm" scope="request"
 * @struts.action-forward name="success" path="/Success?status=Services Registered Successfully"
 * @struts.action-forward name="fail" path="/Success.jsp?status=Service Registeration Failed"
 */
public class BankServiceMasterAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		try{
			BankServicesMasterForm BankServicesMasterForm = (BankServicesMasterForm) form;// TODO Auto-generated method stub
		
		BankServicesMasterDao dao=new BankServicesMasterDao();
		 boolean flag=dao.insertBankServicesMaster(BankServicesMasterForm);
		 if(flag){
			 return mapping.findForward("success");
		 }
	}catch (Exception e) {
		// TODO: handle exception
	}
	return mapping.findForward("fail");
}
}