/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.SBIBanking.dao.*;
import com.dts.SBIBanking.model.BranchServcesMaster;

/** 
 * MyEclipse Struts
 * Creation date: 02-13-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class BranchServiceAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
	try{
		BranchServcesMaster aform=(BranchServcesMaster)form;
		BranchServiceDAO adao=new BranchServiceDAO();
		System.out.println("form"+form);
		boolean flag=adao.register(aform);
		if(flag)
		{
			return mapping.findForward("success");
		}
	}catch (Exception e) {
		// TODO: handle exception
	}
	return mapping.findForward("fail");
	}
}