/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.dae.dao.SecurityDAO;
import com.dts.dae.model.Profile;

/** 
 * MyEclipse Struts
 * Creation date: 02-27-2009
 * 
 * XDoclet definition:
 * @struts.action
 */
public class ChangePassword extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try{
			Profile rb = new Profile();
	        rb.setPassword(request.getParameter("oldpassword"));
	        rb.setLoginID(request.getParameter("username"));
	        rb.setNewPassword(request.getParameter("newpassword"));
	        
	        boolean flag=new SecurityDAO().changePassword(rb);
	            if(flag)
	            {
	            	return mapping.findForward("success");
	            }
		
		}catch (Exception e) {
			e.printStackTrace();
			// TODO: handle exception
		}
		return mapping.findForward("fail");
	}
}