/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.dae.dao.ProfileDAO;
import com.dts.dae.model.Profile;

/** 
 * MyEclipse Struts
 * Creation date: 02-17-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/Success1.jsp?status=Employee Details Updated Successfully""
 * @struts.action-forward name="fail" path="/Success1.jsp?status=Employee Details Updated Failed"
 */
public class EmployeeUpdateProfile extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
try{		Profile aprofile=(Profile)form;

	boolean flag=new ProfileDAO().modifyProfile(aprofile);
	if(flag)
	{
		return mapping.findForward("success");
	}
	else{
		return mapping.findForward("fail");
	}
	}catch (Exception e) {
		// TODO: handle exception
	}
	return mapping.findForward("fail");
}
}