/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;
import com.dts.SBIBanking.dao.BankAccountDAO;
import com.dts.SBIBanking.model.*;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-17-2009
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="success" path="/Success2.jsp?status=Funds Transfered Successfully"
 * @struts.action-forward name="fail" path="/Success2.jsp?status=Funds Transfered Failed"
 */
public class FundsTransferAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try{
			FundsTransferModel amodel=(FundsTransferModel)form;
			BankAccountDAO adao=new BankAccountDAO();
			boolean flag=adao.updateFundsTransfer(amodel);
			if(flag)
			{
				return mapping.findForward("success");
			}
		}catch (Exception e) {
			e.printStackTrace();
			// TODO: handle exception
		}
		return mapping.findForward("fail");
	}
}