/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.dae.dao.ProfileDAO;
import com.dts.dae.model.Profile;

/** 
 * MyEclipse Struts
 * Creation date: 02-16-2009
 * 
 * XDoclet definition:
 * @struts.action path="/registerAction" name="profile" scope="request"
 * @struts.action-forward name="success" path="/Success.jsp"
 * @struts.action-forward name="fail" path="/Fail.jsp"
 */
public class RegisterAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
	try{
		Profile rb = (Profile) form;// TODO Auto-generated method stub
		
      
        boolean flag=new ProfileDAO().registration(rb);
        if(flag)
        {
        	return mapping.findForward("registerSuccess");
        }
    
	}catch (Exception e) {
		e.printStackTrace();
		// TODO: handle exception
	}
	return mapping.findForward("registerFail");
}
}