/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.SBIBanking.dao.StopPaymentDAO;
import com.dts.SBIBanking.model.StopPaymentModule;

/** 
 * MyEclipse Struts
 * Creation date: 02-26-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/Success1.jsp?status=cheque Payment Stopped"
 * @struts.action-forward name="fail" path="/Success1.jsp?status=Cheque Payment Stopped Failed"
 */
public class StopPaymentAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		try{
			StopPaymentModule amodel=(StopPaymentModule)form;
			StopPaymentDAO adao=new StopPaymentDAO();
			boolean flag=adao.register(amodel);
			if(flag)
			{
				return mapping.findForward("success");
			}
		}catch (Exception e) {
			e.printStackTrace();
			// TODO: handle exception
		}
		// TODO Auto-generated method stub
		return mapping.findForward("fail");
	}
}