/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.SBIBanking.dao.ChequeBookRequest;
import com.dts.SBIBanking.model.BankChequeRequestForm;
import com.dts.core.util.CoreList;

/** 
 * MyEclipse Struts
 * Creation date: 02-25-2009
 * 
 * XDoclet definition:
 * @struts.action
 */
public class ViewChequeBookRequest extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try{
			BankChequeRequestForm aform=(BankChequeRequestForm)form;
			ChequeBookRequest crequest=new ChequeBookRequest();
			CoreList acorelist=crequest.viewChequebookrequests();
			int size=acorelist.size();
			if(size!=0)
			{
				request.setAttribute("ViewChequebook",acorelist);
			return mapping.findForward("ViewChequebook");
			}
			
		}catch (Exception e) {
			e.printStackTrace();
			// TODO: handle exception
		}return mapping.findForward("norecords");
	}
}